In [246]:
import pandas as pd 
import numpy as np
from src.utility import get_logger, config, CustomException

In [247]:
data_path = config.load('data_source')['data']['data_source']
project_root = config.config_dir.parent
data_path = project_root / data_path

In [248]:
df = pd.read_csv(data_path)

In [249]:
df.head()

,Status,Seniority,Home,Time,Age,Marital,Records,Job,Expenses,Income,Assets,Debt,Amount,Price
0,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [250]:
df.columns = df.columns.str.lower()

In [251]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [252]:
status_values = {1:'ok',
                2: 'default',
                0 : 'unk'
               } 

df.status = df.status.map(status_values)

In [253]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,1,60,30,2,1,3,73,129,0,0,800,846
1,ok,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,default,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,ok,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,ok,0,1,36,26,1,1,1,46,107,0,0,310,910

In [254]:
home_vale = {
    1:'rent',
    2: 'owner',
    3: 'private',
    4: 'ignore',
    5 : 'parents',
    6 : 'other',
    0 : 'unk'
}
df.home = df.home.map(home_vale)

In [255]:
marital_values = {
    1:'single',
    2: 'married',
    3: 'widow',
    4: 'separated',
    5 : 'divorced',
    6 : 'other',
    0 : 'unk'
}
df.marital = df.marital.map(marital_values)

In [256]:
records_values = {
    1:'no',
    2: 'yes',
    0 : 'unk'
}
df.records = df.records.map(records_values)

In [257]:
job_values = {
    1:'fixed',
    2: 'partime',
    3: 'freelance',
    4:'others',
    0 : 'unk'
}
df.job = df.job.map(job_values)

In [258]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no,freelance,73,129,0,0,800,846
1,ok,17,rent,60,58,widow,no,fixed,48,131,0,0,1000,1658
2,default,10,owner,36,46,married,yes,freelance,90,200,3000,0,2000,2985
3,ok,0,rent,60,24,single,no,fixed,63,182,2500,0,900,1325
4,ok,0,rent,36,26,single,no,fixed,46,107,0,0,310,910

In [259]:
df.describe()

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4455.000000,4455.000000,4455.000000,4455.000000,4.455000e+03,4.455000e+03,4.455000e+03,4455.000000,4455.000000
mean,7.987205,46.441751,37.077666,55.568799,7.633170e+05,1.060341e+06,4.043820e+05,1039.021773,1462.875645
std,8.173444,14.655225,10.984856,19.515878,8.703625e+06,1.021757e+07,6.344253e+06,474.543007,628.089913
min,0.000000,6.000000,18.000000,35.000000,0.000000e+00,0.000000e+00,0.000000e+00,100.000000,105.000000
25%,2.000000,36.000000,28.000000,35.000000,8.000000e+01,0.000000e+00,0.000000e+00,700.000000,1117.500000
50%,5.000000,48.000000,36.000000,51.000000,1.200000e+02,3.500000e+03,0.000000e+00,1000.000000,1400.000000
75%,12.000000,60.000000,45.000000,72.000000,1.660000e+02,6.000000e+03,0.000000e+00,1300.000000,1692.000000
max,48.000000,72.000000,68.000000,180.000000,1.000000e+08,1.000000e+08,1.000000e+08,5000.000000,11140.000000

In [260]:
df.income.max()

99999999

In [261]:
for c in ['income', 'assets', 'debt']:
    df[c] = df[c].replace(to_replace=99999999, value=np.nan)
print("New max income:", df['income'].max())

New max income: 959.0

In [262]:
df.income.max()

959.0

In [263]:
df.status.value_counts()

status
ok         3200
default    1254
unk           1
Name: count, dtype: int64

In [264]:
df = df[df.status != 'unk'].reset_index(drop=True)

In [265]:
df.status.value_counts()

status
ok         3200
default    1254
Name: count, dtype: int64

In [266]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no,freelance,73,129.0,0.0,0.0,800,846
1,ok,17,rent,60,58,widow,no,fixed,48,131.0,0.0,0.0,1000,1658
2,default,10,owner,36,46,married,yes,freelance,90,200.0,3000.0,0.0,2000,2985
3,ok,0,rent,60,24,single,no,fixed,63,182.0,2500.0,0.0,900,1325
4,ok,0,rent,36,26,single,no,fixed,46,107.0,0.0,0.0,310,910

In [267]:
from sklearn.model_selection import train_test_split

In [268]:
df_full_train, df_test = train_test_split(df,test_size = 0.2,random_state=40)
df_train, df_val = train_test_split(df_full_train,test_size=0.25,random_state=40)

In [269]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [270]:
df_train

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,11,owner,12,51,married,no,freelance,45,80.0,6000.0,0.0,1000,1931
1,default,19,owner,60,37,single,yes,fixed,35,115.0,10000.0,6000.0,1500,1758
2,ok,40,owner,24,60,married,no,freelance,75,186.0,8000.0,0.0,900,1307
3,ok,4,owner,60,31,married,no,fixed,60,177.0,3000.0,0.0,1300,1409
4,ok,1,owner,24,47,married,no,fixed,90,188.0,9000.0,0.0,700,1318
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2667,ok,15,owner,48,29,married,yes,fixed,35,100.0,8500.0,1300.0,500,873
2668,ok,15,private,24,52,single,no,freelance,35,330.0,16500.0,0.0,1500,2201
2669,ok,3,owner,18,24,married,no,partime,45,185.0,3500.0,0.0,600,925
2670,default,8,rent,48,30,single,no,fixed,46,114.0,0.0,0.0,1650,1659
2671,ok,2,parents,36,30,married,yes,partime,60,203.0,0.0,0.0,600,1549

In [271]:
y_train= (df_train.status =='default').astype('int').values
y_val= (df_val.status =='default').astype('int').values
y_test= (df_test.status =='default').astype('int').values

In [272]:
y_train

array([0, 1, 0, ..., 0, 1, 0])

In [273]:
del df_train['status']
del df_val['status']
del df_test['status']

In [274]:
df_train.head()

,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,11,owner,12,51,married,no,freelance,45,80.0,6000.0,0.0,1000,1931
1,19,owner,60,37,single,yes,fixed,35,115.0,10000.0,6000.0,1500,1758
2,40,owner,24,60,married,no,freelance,75,186.0,8000.0,0.0,900,1307
3,4,owner,60,31,married,no,fixed,60,177.0,3000.0,0.0,1300,1409
4,1,owner,24,47,married,no,fixed,90,188.0,9000.0,0.0,700,1318

In [282]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import roc_auc_score

In [278]:
train_dicts = df_train.fillna(0).to_dict(orient='records')
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)
X_train

array([[5.10e+01, 1.00e+03, 6.00e+03, ..., 0.00e+00, 1.10e+01, 1.20e+01],
       [3.70e+01, 1.50e+03, 1.00e+04, ..., 1.00e+00, 1.90e+01, 6.00e+01],
       [6.00e+01, 9.00e+02, 8.00e+03, ..., 0.00e+00, 4.00e+01, 2.40e+01],
       ...,
       [2.40e+01, 6.00e+02, 3.50e+03, ..., 0.00e+00, 3.00e+00, 1.80e+01],
       [3.00e+01, 1.65e+03, 0.00e+00, ..., 0.00e+00, 8.00e+00, 4.80e+01],
       [3.00e+01, 6.00e+02, 0.00e+00, ..., 1.00e+00, 2.00e+00, 3.60e+01]])

In [280]:
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [281]:
val_dict = df_val.fillna(0).to_dict(orient='records' )
X_val = dv.transform(val_dict)

In [284]:
y_pred = dt.predict_proba(X_val)[:,1]
y_pred

array([0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1.,
       0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
       0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1.,
       0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0.])

In [285]:
roc_auc_score(y_val,y_pred)

0.6592078189300412

In [286]:
y_predic = dt.predict_proba(X_train)[:,1]

In [287]:
roc_auc_score(y_train,y_predic)

1.0

In [296]:
dt = DecisionTreeClassifier(max_depth = 4)
dt.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=4)

In [297]:
val_dict = df_val.fillna(0).to_dict(orient='records' )
X_val = dv.transform(val_dict)
y_pred = dt.predict_proba(X_val)[:,1]
roc_auc_score(y_val,y_pred)

0.7705697810293146

In [298]:
roc_auc_score(y_train,y_predic)

1.0

In [299]:
from sklearn.tree import export_text

In [300]:
feature_names = list(dv.get_feature_names_out())

In [301]:
tree_rules = export_text(dt, feature_names=feature_names)
print(tree_rules)

|--- seniority <= 2.50
|   |--- records=yes <= 0.50
|   |   |--- income <= 88.50
|   |   |   |--- time <= 27.00
|   |   |   |   |--- class: 0
|   |   |   |--- time >  27.00
|   |   |   |   |--- class: 1
|   |   |--- income >  88.50
|   |   |   |--- job=partime <= 0.50
|   |   |   |   |--- class: 0
|   |   |   |--- job=partime >  0.50
|   |   |   |   |--- class: 1
|   |--- records=yes >  0.50
|   |   |--- amount <= 925.00
|   |   |   |--- price <= 853.00
|   |   |   |   |--- class: 1
|   |   |   |--- price >  853.00
|   |   |   |   |--- class: 0
|   |   |--- amount >  925.00
|   |   |   |--- job=fixed <= 0.50
|   |   |   |   |--- class: 1
|   |   |   |--- job=fixed >  0.50
|   |   |   |   |--- class: 1
|--- seniority >  2.50
|   |--- records=yes <= 0.50
|   |   |--- income <= 100.50
|   |   |   |--- expenses <= 62.00
|   |   |   |   |--- class: 0
|   |   |   |--- expenses >  62.00
|   |   |   |   |--- class: 0
|   |   |--- income >  100.50
|   |   |   |--- assets <= 1650.00
|   |   |   |   |--- class: 0
|   |   |   |--- assets >  1650.00
|   |   |   |   |--- class: 0
|   |--- records=yes >  0.50
|   |   |--- income <= 107.50
|   |   |   |--- assets <= 5250.00
|   |   |   |   |--- class: 1
|   |   |   |--- assets >  5250.00
|   |   |   |   |--- class: 0
|   |   |--- income >  107.50
|   |   |   |--- marital=separated <= 0.50
|   |   |   |   |--- class: 0
|   |   |   |--- marital=separated >  0.50
|   |   |   |   |--- class: 1